name: 'Deploy S3 Bucket'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  delete_bucket:
    description: 'Run command to delete the bucket'
    default: ''

  sync_bucket:
    description: 'Run command to sync the bucket'
    default: ''

  AWS_ACCESS_KEY_ID:
    required: true

  AWS_SECRET_ACCESS_KEY:
    required: true

  INVALIDATE_DIST:
    required: true

  INVALIDATE_PATHS:
    default: '/*'

runs:
  using: 'composite'

  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deleting Bucket
      if: ${{ inputs.delete_bucket != '' }}
      # run: inputs.delete_bucket
      run: |
        declare -a arr=${{ inputs.delete_bucket }}
        for i in "${arr[@]}"
        do
          echo "_aws s3 rm $i"
          aws s3 rm $i
        done
      shell: bash

    - name: Deploying Bucket
      id: deploy_bucket
      if: ${{ inputs.sync_bucket != '' }}
      run: |
        declare -a arrSync=${{ inputs.sync_bucket }}
        for i in "${arrSync[@]}"
        do
          echo "_aws s3 sync $i"
          aws s3 sync $i
        done
      shell: bash

    - name: Testing
      run: echo ${{ inputs.DISTRIBUTION }}
      shell: bash

    # Invalidate Cloudfront
    - name: Creating invalidation
      if: ${{ inputs.DISTRIBUTION }}
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ inputs.INVALIDATION_DIST }}
        PATHS: ${{ inputs.INVALIDATE_PATHS }}
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
