name: 'Deploy S3 Bucket'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  remove_bucket:
    description: 'Run command to delete the bucket'
    default: ''

  sync_bucket:
    description: 'Run command to sync the bucket'
    default: ''

  AWS_ACCESS_KEY_ID:
    required: true

  AWS_SECRET_ACCESS_KEY:
    required: true

  INVALIDATE_DIST:
    required: true

  INVALIDATE_PATHS:
    default: '/*'

runs:
  using: 'composite'

  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash     

    - name: Deleting Bucket
      if: ${{ inputs.remove_bucket != '' }}
      run: deployBucket.sh "${{ inputs.remove_bucket }}" remove
      shell: bash

    - name: Deploying Bucket
      id: deploy_bucket
      if: ${{ inputs.sync_bucket != '' }}
      run: deployBucket.sh "${{ inputs.sync_bucket }}" sync
      shell: bash

    # Invalidate Cloudfront
    - name: Creating invalidation
      if: ${{ inputs.INVALIDATE_DIST }}
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ inputs.INVALIDATE_DIST }}
        PATHS: ${{ inputs.INVALIDATE_PATHS }}
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
